chef-cookbooks/chef_client_updater

metadata.rb
Point to the new project repo instead of the previous project on which this cookbook was based.
- ~New functionality includes testing.~
- ~New functionality has been documented in the README if applicable~
=> point the URLs at the new project repo

libraries/matchers.rb
I'm not sure about name, but I'm following convention. However I would prefer just `update_chef_client`.
Signed-off-by: Szymon Szypulski <szymon.szypulski@gmail.com>
=> Add ChefSpec matcher

.kitchen.yml, README.md, attributes/default.rb, recipes/default.rb, resources/updater.rb
Add support for download URL overrides
N/A
=> Add support for download URL overrides

resources/updater.rb
=> Add the workaround for windows we used in omnibus_updater

.kitchen.dokken.yml, .travis.yml, providers/default.rb, test/cookbooks/test/recipes/constrained.rb
=> Fix partial version infinite loop

providers/default.rb
also merges in the windows fixes in #18 with considerable refactoring
=> clean up /opt/chef before reinstalling

Gemfile, providers/default.rb
for now i'm not quite clever enough to figure out an automated test, but this passes on my desktop.
closes #24
=> Rollback /opt/chef.upgrade to /opt/chef on failure

README.md
Signed-off-by: Steven Murawski <steven.murawski@gmail.com>
Updated README with Windows 11 and Windows service update specifics and examples.
=> Windows details to the readme

README.md
=> fix doc for prevent_downgrade

CHANGELOG.md, metadata.rb
Cut a release for our airgapped users.
Signed-off-by: Seth Thomas <sthomas@chef.io>
=> Release 2.0.2

providers/default.rb
=> work around mixlib-install returning scalar-or-array

README.md
=> [ci skip] fix windows task example in README

metadata.rb
=> bump version to 3.0.0 to stage for release

providers/default.rb
Mostly just debug stuff I added in troubleshooting life
=> Fix incorrect rubygems upgrade message + add debug messages

providers/default.rb
This fixes converge logging so that we get the correct version that is being installed instead of "12" when a user specifies a partial version. It also gives us way more debug logging
=> Move all version parsing for desired version into a single method to fix logging

.kitchen.yml, chefignore
=> Testing Updates

providers/default.rb, test/cookbooks/test/recipes/kill.rb
=> Require a mixin-install that supports proxies

providers/default.rb, resources/default.rb
Signed-off-by: Robbert-Jan Sperna Weiland <rspernaweiland@schubergphilis.com>
This PR adds support on Windows for downgrading the Chef client version.
#64
=> Support for downgrading the Chef client on Windows

CHANGELOG.md, attributes/default.rb, metadata.rb, providers/default.rb
Signed-off-by: Yury Levin <iamyura@gmail.com>
[Describe what this change achieves]
=> Add custom upgrade delay.

.kitchen.dokken.yml, README.md, providers/default.rb, test/cookbooks/test/attributes/default.rb, test/integration/default/default_spec.rb, test/integration/noop/noop_spec.rb
=> Improve how we handle updating rubygems

spec/unit/recipes/default_spec.rb
=> Use new ChefSpec format

.travis.yml, Gemfile, README.md, attributes/default.rb, kitchen.dokken.yml, kitchen.yml, providers/default.rb, test/cookbooks/test/recipes/license.rb, test/integration/license/license_spec.rb, test/integration/noop/noop_spec.rb
See README for how to accept the license.
N/A
=> Adding license acceptance support

CHANGELOG.md, metadata.rb, providers/default.rb
Fixed eventlog restart so Chef converge doesn't fail
- [ x All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [ x] New functionality includes testing.
- [x ] New functionality has been documented in the README if applicable
=> Fixed eventlog restart so Chef converge doesn't fail

providers/default.rb
- On Windows, check for previously installed version contains unwanted carriage return.
current_version was returning version with carriage return character that affected Mixlib::Versioning.parse. We had to trim it off.
- Fix while upgrading ChefDK from 3 to 4.
Prior to 4, "ChefDK Version" was displayed as "Chef Development Kit Version". Due to this verbiage change, it was not identifying installed version of Chef DK if it is v4+. Updated RegEx for this fix.
- Installs ChefDK if it was never installed previously
Signed-off-by: Nimesh-Msys <nimesh.patni@msystechnologies.com>
#147
=> Minor Fixes while upgrading ChefDK

providers/default.rb
fix windows chef install path
obvious fix
=> fix windows chef install path

providers/default.rb
Necessary changes in PS script to accept the chef-client license while chef client upgrade in Windows.
Signed-off-by: Nimesh-Msys <nimesh.patni@msystechnologies.com>
- Using [license_acceptance/acceptor](https://github.com/chef/license-acceptance/tree/master/components/ruby#usage) to accept and persist the license.
Closes #170
=> Accept and persist license while upgrading in windows OS

attributes/default.rb
This removes non-idiomatic `(...).to_s` call from code
N/A
=> Remove #to_s conversion

providers/default.rb
Signed-off-by: Tom Pitman <tom@pitmania.net>
Provides a more robust eventlog and dependent services restart experience, by attempting to perform orderly shutdown and restart of eventlog and associated dependent services.
Fixes: #179
=> more robust eventlog and dependent services restart

providers/default.rb
=> Updates for supporting Cinc

README.md
Fixed while reading this over to understand if we mixed something
=> Consistent branding in the readme

README.md, attributes/default.rb, providers/default.rb, recipes/default.rb, resources/default.rb, test/cookbooks/test/recipes/license.rb
Marketing rules everything around us
=> More chef-client / chef -> Chef Infra Client

providers/default.rb
1) Fixed identified defect where $taskScheduler was being used without being fully initialized. The erroring code was ultimately removed due to refactoring to use the Task Scheduler cmdlets introduced in Windows PowerShell 3.0. 
2) Using the cmdlets allowed addition of 'StartWhenAvailable' which, when enabled, means the task will run as soon as possible after the trigger time has passed. Previously the task would not have run if the system were rebooting at scheduled time. 
2) Updated the start time of the new trigger to be based on the current time rather than the time the trigger last occurred. Task will run $minutes into the future rather than $minutes from the last trigger.
3) Minor spelling correction
No automated tests for this code existed and no automated tests were added. This …
=> #209 Fixed Windows PowerShell task reschedule

providers/default.rb
Signed-off-by: gscho <greg.c.schofield@gmail.com>
By bumping mixlib-install so that download url overrides can contain query parameters.
=> Bump version of mixlib-install

providers/default.rb
Signed-off-by: Robert Detjens <detjensrobert@osuosl.org>
As recommended instead of #235.
=> Disable unified_mode if present

providers/default.rb
Remove unified_mode in incorrect place
=> Remove unified_mode
