chef-cookbooks/chef_client_updater

.travis.yml, README.md
lowest version that chef_zero provisioner of test-kitchen works
with (and likely that kitchen-dokken works with)
=> lower testing to chef-11.10.4

providers/default.rb
There were several problems that blocked this from working on Windows.
First, since platform and architecture weren't being supplied to mixlib-install, it was trying to run the bash script to install Chef.  That no work.
Second, after changing it to make mixlib-install generate the powershell scripts, the command was too long for mixlib-shellout to execute.
Third, most of the operations were in ruby, so they were happening at compile time inside the resource. The execute block to move the directories never got called because Process.exit was happening first.
Making the execute block that moved directories happen earlier required moving the generation of the mixlib-install script before that, as the attempt to `require` mixlib-install would fail if the move happened first.
Yay for …
=> Support for Windows

providers/default.rb
when forcing to run at compile time we should always no-op the
running at converge time.
Signed-off-by: Lamont Granquist <lamont@scriptkiddie.org>
=> add run_action :nothing

providers/default.rb
Make  chef_client_updater work again in air-gapped environments
=> Make  chef_client_updater work again in air-gapped environments

providers/default.rb
- uses code adapted from chef-ingredient cookbook
Signed-off-by: Doc Walker <4-20ma@wvfans.net>
Fixes platform detection for `centos`
#31 
- [N/A] New functionality includes testing.
- [N/A] New functionality has been documented in the README if applicable
* Syntax check fails due to existing issue unrelated to this PR:
```
FC023: Prefer conditional attributes: ./providers/default.rb:229
Phase failed with exit code (3)!
```
=> Fix #31 detect centos platform correctly

attributes/default.rb
the attribute and the resource defaults disagree and that is confusing
and needs to be fixed.
this is the correct setting for configuration management.  to do config
management correctly you should be expressing your requirements as
equality pins.  if you have a later version installed you actually do
want to downgrade it.
otherwise you will not have consistent bugs across your production
environment, and your testing on any given version will be invalid.
to allow later versions on your systems means you are trusting that
i never write code which introduces bugs -- thank you for the vote of
confidence, but you're so very, very wrong.
this change will change behavior for some users.  perhaps surprsingly,
so we might already need to do a major bump to 3.0.0 here.
closes #44
=> change prevent_downgrade attribute to false to match resource+docs

README.md, attributes/default.rb, providers/default.rb, resources/default.rb, test/cookbooks/test/recipes/constrained.rb, test/cookbooks/test/recipes/default.rb, test/cookbooks/test/recipes/direct_url.rb
kill seems to clean up a lot of garbage that exec would leave behind.
=> change default to 'kill' from 'exec'

providers/default.rb
Signed-off-by: Trevor Hess <trevor@chef.io>
This allows Chef Client 13 to be upgraded on Windows machines
Chef Client 13 has changed how the gem executable is deployed on Windows. It is no longer gem, but gem.cmd
Tests will be added in a separate commit, as there are currently not tests in this cookbook outside of harness cookbooks. And no integrated test for Windows exists yet. I did test myself in Azure.
- [ x] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>
=> adding check for gem.cmd on chefclient 13 windows

providers/default.rb
Before we would just silently not use the override URL which isn't very helpful
=> Raise if download_url_override is set but checksum isn't

.kitchen.yml, chefignore, metadata.rb, providers/default.rb, test/cookbooks/test/attributes/default.rb, test/cookbooks/test/recipes/default.rb, test/cookbooks/test/recipes/kill.rb, test/integration/default/default_spec.rb
Basically upgrading by moving the Chef install directory on windows had a high failure rate. This changes the move to copy-and-cleanup-in-next-run.
This includes the changes in https://github.com/chef-cookbooks/chef_client_updater/pull/67 but squashed in one commit. 
Also updates testing.
File locks within the C:\opscode\Chef folder potentially result in a corrupt Chef install on Windows systems. The use of Ruby FileUtils.mv iterates over the folder subitems, moving unlocked files to dest folder but leaving locked files in src folder. This effectively breaks the Chef install.
The Powershell Rename-Item function does all-or-nothing. So you end up with the new version, or your old version will still be intact.
the Chef run doing the upgrade itself locks some DLLs in the embedded/bin folder …
=> Improved updating on windows and adds integration test

providers/default.rb
Signed-off-by: Charlie Roffe <charlie@roffe.net>
Increases effectiveness of upgrade scheduled task.  Previously, upgrade scheduled task would fail if Powershell Execution Policy is too restricted.  This will bypass the Powershell Execution Policy for the upgrade.
https://github.com/chef-cookbooks/chef_client_updater/issues/75
=> Windows: Bypass Powershell Execution Policy for upgrade scheduled task

attributes/default.rb, providers/default.rb
We use Chef to manage the internal build infrastructure which is used to build Chef. In order to have a reliable chef-client and reproducible builds we use "angrychef" on these nodes which installs under
`/opt/angrychef` rather than the default `/opt/chef` path.
- Issue #68 
/cc  @jaymalasinha @scotthain @schisamo @tduffield
=> Alow custom paths to chef-client.

.kitchen.yml, providers/default.rb, test/cookbooks/test/recipes/noop.rb
If someone gives us these we do need to lookup a full version string:
12.5
12
:latest
If someone gives us this we don't:
12.13.7
This removes load on our systems, speeds up the run, and allows the run to continue if those servers are down.
=>  If the user provides an X.Y.Z format version don't contact omnitruck

providers/default.rb
This change makes it so if there is an error install chef with the shell snippet Mixlib::Install generates it will fail the chef run. Currently if it fails it will silently ignore and continue. This causes all sorts of havoc like the chef-client command no longer working. 
=> error out chef run if shell update fails

recipes/default.rb
Signed-off-by: Yury Levin <iamyura@gmail.com>
This commit resolves issue with warning
$$$$$$ chef-client.bat : WARNING: Task may not run because /ST is earlier than current time.
described at https://github.com/chef-cookbooks/chef_client_updater/pull/87#issuecomment-360745209
This issue probably prevents Chef client from being upgraded.
=> Fix warning '/ST is earlier than current time'

.travis.yml, providers/default.rb
Signed-off-by: Scott Hain <shain@chef.io>
Sometimes chef-client doesn't respect the TERM signal and will be left orphaned on a machine. This is highly problematic when you upgrade regularly.
=> Use KILL instead of TERM on Windows

README.md, recipes/default.rb, resources/default.rb
Change default upgrade delay to 61 seconds.
This eliminate warning "Task may not run because /ST is earlier than current time." that still might appear if task is being scheduled within 1-30 seconds of any minute and if default delay 30 seconds is used.
=> Change default upgrade delay to 61 seconds.

providers/default.rb
In #94 we changed the signal from TERM to KILL but the log message still
indicates that we're sending a TERM. This change aligns the log with the signal.
=> Update log message to KILL from TERM

providers/default.rb, recipes/default.rb
Normally we rely on a supervisor to restart chef-client after upgrade,
but in this case we can try to restart under sysvinit by using cron to
schedule the service to start again.
=> Restart chef-client with cron under sysvinit

providers/default.rb
Signed-off-by: Scott Hain <shain@chef.io>
When `node['chef_client_updater']['chef_install_path']` is specified, `chef_install_path` resolves to 'c:/opscode/chef'
=> Fix custom install path

providers/default.rb
can't use node.read() 'cuz chef-11.
this happens if the user is not using the chef-client cookbook
closes #106
=> protect against nil node attrs

providers/default.rb
* stopped Push Jobs service before upgrading
* added exit message
Signed-off-by: Annie Hedgpeth <annie.hedgpeth@gmail.com>
This changes stops the Push Jobs service since it uses `ruby.exe`.
#108 
- [n/a] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
_Can't load the bento boxes on my workstation._
_Ran the ps1 manually on a node that had Push Jobs running._
- [n/a] New functionality has been documented in the README if applicable
=> [GH-108] - stopped Push Jobs

README.md, providers/default.rb
This change does two things:
* Further clarifies the relatively [new](https://github.com/chef-cookbooks/chef_client_updater/pull/102) `restart_chef_via_cron` functionality in the `README.md`
* Introduces a Platform case statement for defining the command necessary to restart the service via the cron job. 
For AIX, the `chef-client` cookbook activates the service via the SRC init style. This init system requires a specific command to start which is different from the typical `/etc/init.d/chef-client start` of Sys-V systems. 
The Platform case statement handles this difference and could also be used for other platforms as well 😃 
This PR removes the `minute` property from the cron job, since the original format of `minute '*/1'` is not compatible on all systems, such as AIX. This is OK …
=> handle cron job service restart on AIX

providers/default.rb, recipes/default.rb, test/cookbooks/test/attributes/default.rb
When I was running a wrapper cookbook using the chef_client_updater resource directly and not the default recipe, the cron job that is put in place during an upgrade never got deleted and chef-client was running every minute! 
To prevent this from happening, this pull request puts the cron job deletion code into the cleanup function of the resource so it gets run no matter the method you choose to use this cookbook.
I also updated the chef-client version in the test cookbook so the tests would run when I was trying to test these.
No Issues that are already reported
=> Move cron deletion to cleanup function of resource

providers/default.rb
The 3.3.4 version of this cookbook adds an EventLog service restart for Windows upgrades with the following line in `Chef_upgrade.ps1`:
```
Get-Service EventLog | Restart-Service -Force
```
However, on Windows Server 2008 editions, this is not possible for default functionality. The EventLog service has a dependency on the Task Scheduler service, which cannot be stopped/started/restarted with PowerShell. This bombs out the scheduled task that is to upgrade Chef-client and the system is left with a broken Chef-client installation. Simply skipping the EventLog restart on Windows Server 2008 systems mitigates this.
None
- [ X ] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [ X ] New functionality includes testing.
- [ X ] …
=> Do not attempt EventLog restart on Windows Server 2008

providers/default.rb
Properly detects installed version when updating chefdk by switching to the ohai packages plugin
Resolves #95 
- [N/A] New functionality includes testing.
- [N/A] New functionality has been documented in the README if applicable
=> Fix ChefDK update loop

.kitchen.yml, README.md, providers/default.rb, resources/default.rb, test/cookbooks/test/recipes/gem_server.rb, test/cookbooks/test/recipes/rubygems_url.rb, test/cookbooks/test/templates/default/ufw_chef.erb
Allow the rubygems server to be specified for isolated environments.
Signed-off-by: markgibbons <mark.gibbons@nordstrom.com>
Allow the ruby gems source to be specified.
=> rubygems_url: Allow the rubygems source to be specified

providers/default.rb
This properly detects the final release of Amazon Linux 2.0
=> Require mixlib-install 3.11+ for Amazon Linux 2.0

README.md, providers/default.rb, resources/default.rb, test/cookbooks/test/recipes/default.rb
Signed-off-by: Joshua Justice <jjustice6@bloomberg.net>
Allow package install timeout to be configurable.
On some machines and platforms, it is entirely possible for installing Chef to take more than 10 minutes, while working perfectly fine. We encountered this on some AIX machines in testing. This change would allow for
=> Allow for a configurable package install timeout.

.kitchen.dokken.yml, .travis.yml, test/cookbooks/test/attributes/default.rb, test/cookbooks/test/recipes/constrained.rb, test/integration/default/default_spec.rb
Signed-off-by: Stuart Preston <stuart@chef.io>
Testing addition of cron to dokken image via intermediate instruction
=> Add cron to apt-get intermediate instruction to fix TravisCI tests

providers/default.rb
As I propose in #136, calculate the time 5 minutes from now and pass that as properties to the `cron` resource.
=> only run cron job 5 minutes from "now"

providers/default.rb
we force-upgrade so we have to use this now.
we also force-upgrade so we don't care about back-compat.
=> use --no-document for rubygems 3.0

.travis.yml, providers/default.rb
replaces #144 
when we fail the check on >= 2.6.11  we install 2.7.8 deliberately -- because if you've got super-old rubygems you are getting rudely force-upgraded anyway, and i want to skip over all the possible bugs between 2.6.11 and 2.7.8, which i find more likely than bugs in 2.7.8 on old systems at this point.  this also replicates the existing behavior -- up until it broke with rubygems 3.0 -- so this behavior is actually very well tested.
so the algorithm is:
- if you have >= 2.6.11 we leave it alone (and i don't entirely like this, but i haven't found a reason to force-upgrade these people.... yet...)
- if you have < 2.6.11 (which is all just totally broken) we force upgrade you to 2.7.8 which is the latest that we can get away with without rubygems 3.0 blowing up on very old …
=> fix rubygems 3.0 again

attributes/default.rb, kitchen.yml, providers/default.rb, recipes/default.rb, resources/default.rb, test/cookbooks/test/recipes/no_service_restart.rb
Added attribute `event_log_service_restart ` to restart EventLog service which will give authority for user to restart the service or not.
Which will resolves issue of  "chef_client_updater kills non chef processes on windows during upgrades" and #74 
Backstory #117
=> [MSYS-994] Add event_log_service_restart attribute to fix issue of non chef service restart

README.md, attributes/default.rb, providers/default.rb
Signed-off-by: Stefan Wessels Beljaars <swesselsbeljaars@schubergphilis.com>
Allow path to handle.exe to be configured. This is useful if you already have handle.exe somewhere else on your system.
=> Allow path to handle.exe to be configured

providers/default.rb
Signed-off-by: NAshwini <ashwini.nehate@msystechnologies.com>
While creating cronjob for licence acceptance gets below error:
<details>
[root@ashrhel6 ~]# [2019-09-27T04:49:33-04:00] WARN: Chef Client was upgraded, scheduling chef-client start via cron in 5 minutes
* cron[chef_client_updater] action createKilled
[root@ashrhel6 ~]#
================================================================================
Error executing action `create` on resource 'cron[chef_client_updater]'
================================================================================
Chef::Exceptions::Cron
----------------------
Error updating state of chef_client_updater, error: Expected process to exit with [0], but received '1'
---- Begin output of crontab -u root - ----
STDOUT:
STDERR: "-":3: bad minute …
=> Fix creation of cron error while licence acceptance

attributes/default.rb, recipes/default.rb
Signed-off-by: dheerajd-msys <dheeraj.dubey@msystechnologies.com>
- Sets custom rubygems server which can work when cookbook is being used in air-gapped environment.
- Earlier it was being set to `rubygems.org` by default because of `nil` for `new_resource.rubygems_url` here https://github.com/chef-cookbooks/chef_client_updater/blob/master/providers/default.rb#L34 and causes failure when cookbook is used in an air-gapped environment 
- Test cases/recipes are already written to set `rubygems_url`
Fixes https://getchef.zendesk.com/agent/tickets/20046
=> Allowing custom rubygems server

CHANGELOG.md, metadata.rb, providers/default.rb
[Describe what this change achieves]
Allows use of a no_proxy artifact server to download from when overriding the URL. This works in tandem with: https://github.com/chef/mixlib-install/pull/299
=> Added no_proxy support for override_url

providers/default.rb
Signed-off-by: dheerajd-msys <dheeraj.dubey@msystechnologies.com>
- Replaces chef installation path hard-coded value to variable  `chef_install_dir`
Fixes https://github.com/chef-cookbooks/chef_client_updater/issues/128
=> Replace hardcode value with `chef_install_dir`

providers/default.rb
- Fixes compilation error while upgrading from Chef-12
- Better regex to identify correct ChefDK version: Detecting version within the line
Previous [PR#167](https://github.com/chef-cookbooks/chef_client_updater/pull/167) had some issues related to upgrading from Chef-12. This code avoids using safe navigation operator.
#170
=> Minor Fixes While detecting chef DK version

CHANGELOG.md, README.md, libraries/chef_client_updater_helper.rb, providers/default.rb, resources/default.rb, spec/unit/libraries/chef_client_updater_helper_spec.rb
Add install_command_options to chef_client_updater resource for specifying additional command options when updating chef, such as installing as a scheduled task
Signed-off-by: George Holt <gholtiii@me.com>
The Chef_upgrade task previously would try only once to upgrade chef and would bail if ruby or opscode processes are still running, which is often the case on Windows platform.  The change enables the Chef_upgrade task to try 5 times, sleeping 60 seconds in between.  If it still fails it will reschedule itself 10 minutes in the future from the original task time, enabling it to continue trying to upgrade Chef until it succeeds.
It also adds the install_command_options property to the chef_client_updater, which is necessary to enable the resource to be used to install Chef as a scheduled …
=> Enable chef upgrade to install as scheduled task with install_command_options

providers/default.rb
Fix Windows scheduled task by removing mandatory parameters for WaitForChefClientOrRescheduleUpgradeTask
We call the function bare, so a prompt to supply the input parameters occurs as described by @cdbeard2016 in #172 
https://github.com/chef-cookbooks/chef_client_updater/blob/a27cff51897b9d0a49315b9da8381936312b33e7/providers/default.rb#L482
https://github.com/chef-cookbooks/chef_client_updater/issues/172
=> Fix Windows Upgrade scheduled task

attributes/default.rb, resources/default.rb
Updated the `:rubygems_url` resource to set a default value and removed the `['chef_client]['config']['rubygems_url']` attribute from `attributes/default.rb`. Let me know if something needs to be changed with this
https://github.com/chef-cookbooks/chef_client_updater/issues/176
=> Removed rubygems_url attribute and updated rubygems_url resource

attributes/default.rb, recipes/default.rb
Signed-off-by: dheerajd-msys <dheeraj.dubey@msystechnologies.com>
- Originally attribute `default['chef_client']['config']['rubygems_url']` was added to support mirror/internal rubygems server( But was not honoring the namespacing rules and got merged).
-  Based on https://github.com/chef-cookbooks/chef_client_updater/issues/176#issuecomment-583184795 PR https://github.com/chef-cookbooks/chef_client_updater/pull/180 is created and did not delete the attribute from recipe.
- So this caused `nil:NilClass error` arising from recipe.
- Changed the attribute name to `default['chef_client_updater']['rubygems_url']` in order to support internal rubygems server as well as meeting namespacing rules of the cookbook.
- Comments for reference …
=> Fix `nil:NilClass error` arising due to removal of attribute `rubygems_url` 

providers/default.rb
Signed-off-by: sanga17 <sausekar@msystechnologies.com>
Eventlog restart should also restart dependent services previously stopped
Fixes: https://github.com/chef-cookbooks/chef_client_updater/issues/179
=> Fixed restart eventlog and dependent services

kitchen.yml
Make sure we can run the tests without low memory errors from Windows.
=> Update the kitchen config with win2k19 and additional memory

providers/default.rb
This adds a catch block around the mixlib-install scripts to handle any
exceptions that are thrown. Along with some additional messages so we
know what's currently happening
Also, moves the handle.zip install to earlier in the process so it can fail
before we remove the chef directory.
=> Catch when the windows upgrades fail

providers/default.rb
Signed-off-by: dheerajd-msys <dheeraj.dubey@msystechnologies.com>
This change upgrades the client on non-windows node as well as handles the license acceptance issue specific to when upgrade is done from v13 to v15
-- Setting the attribute `default['chef_client']['chef_license'] = 'accept'` was not working when it was done from `chef v13` to `chef v15`. So this change handles this behaviour and works well on non-windows node.
-- Tested on centos and ubuntu
Fixes https://github.com/chef-cookbooks/chef_client_updater/issues/203
=> Fix license acceptance on non-windows

README.md
Signed-off-by: pratixha <pratiksha.prajapati@msystechnologies.com>
Added docs for windows custom path
Edited documents that windows supports custom path for installing chef-client.
and how to set custom path in attributes
by default it's install location will be c:/opscode
#205
=> Added docs for windows custom path
